export const currencies = [
  { item: 'USD' },
  { item: 'EUR' },
  { item: 'CNY' },
  { item: 'INR' },
  { item: 'CAD' },
  { item: 'GBP' },
  { item: 'JPY' },
  { item: 'RUB' },
  { item: 'MXN' },
  { item: 'CHF' },
  { item: 'KRW' },
  { item: 'TRY' },
  { item: 'BRL' },
  { item: 'SEK' },
  { item: 'HKD' },
  { item: 'ETH' },
  { item: 'AUD' },
  { item: 'NOK' },
  { item: 'SGD' },
  { item: 'BTC' },
];
